### ISSUE TITLE
Make RMD file compatible with the test data

### ISSUE THREAD

**Issue by najsaqib** [bcgov/WES_engagement_states#13] opened 2016-11-10 22:17 UTC
Related to #7

**Comment by najsaqib** [comment] 2016-11-10 22:38
@daattali so I made changes to the RMD file to make it work with the new dataset. Also, I've added the code required to first read the new mock dataset and then save a new file, that is in turn being used to populate the tables in the RMD file. That code is added to the global.R file in the "shiny" folder, which may or may not be the appropriate place to put it.  It only needs to be run once (i.e. whenever the finalMockData.csv file is replaced with the real data file, or is updated in the future with new data).

**Comment by daattali** [comment] 2016-11-10 23:03
Thanks for letting me know!
1. I wouldn't recommend putting that code in global.R, because that means it'll get run every time the app starts. If it's code that only needs to be run once whenever the data changes, it should probably go in a separate file with a filename that makes it clear it should only run (manually?) when the main data file changes.
2. To clarify: this means that there are now 2 different data files used in the app (where one of the data files is derived from the other), correct? How long does it take to run this data transforming pipeline to create the second file? If it's very quick (well under 1second), I personally would prefer to have the data transformation happen inside the Rmd rather than introduce a new file dependency. It's not a big deal obviously to have just one more file, but if every plot that needs a different format of the data would create a new data file, we'll soon have a few more files that all have the same data just transformed differently. It's not a big deal, just not a great practice. We can keep it as-is, I just wanted to point this out.

Point 1 about placing the code in a different file is much more important and I feel more strongly about, point 2 is more about style and better maintainability (less important, I won't push it :smile:  )

**Comment by najsaqib** [comment] 2016-11-10 23:21
Good call. I just profiled the relevant block of code and apparently it does not take that long to execute:

![profvis](https://cloud.githubusercontent.com/assets/22086214/20198242/6af315a4-a758-11e6-816d-e6299f098abb.PNG)

Given that it only takes 0.44 seconds in total (can easily be made a tad quicker still), I will proceed to shoehorn the code inside the Rmd file instead of the global.R file. I am definitely all for keeping things neat and tidy as much as possible. :+1:

**Comment by daattali** [comment] 2016-11-11 00:22
Cool. It's definitely more of a judgment call. And nice to see the new profiler in use!

**Comment by daattali** [comment] 2016-11-13 01:52
@najsaqib the Rmd file in its current state reads from a file named "combinedStates.rds", but no such file exists in the repo. Is it supposed to be identical to the existing rds file just with a different name?

**Comment by daattali** [comment] 2016-11-13 01:55
Oh sorry I see now - that's the file that gets generated in global.R.  So it won't be needed anymore after you address the issues above.

**Comment by najsaqib** [comment] 2016-11-16 19:29
ccb7127741d68bac892e67812272428becb620f2 The data file is now being read within the Rmd file and all the necessary manipulations (including turning 6 engagement states into 4) are happening within. Performance seems OK to me. On my machine at least, the knitting is not taking perceivably longer than before, which is definitely good.

**Comment by daattali** [comment] 2016-11-20 07:55
I can confirm it works for me too, so closing this issue as done

**Closed as completed by daattali** 2016-11-20 07:55 UTC
